

export const API_ROOT = 'http://localhost:8080'


export const MODAL_ACTION_CLOSE = 'MODAL_ACTION_CLOSE'
export const MODAL_ACTION_CONFIRM = 'MODAL_ACTION_CONFIRM'

export const USER_SELECT_POPOVER_TYPE_BOARD_MEMBERS = 'USER_SELECT_POPOVER_TYPE_BOARD_MEMBERS'
export const USER_SELECT_POPOVER_TYPE_CARD_MEMBERS = 'USER_SELECT_POPOVER_TYPE_CARD_MEMBERS'
